### ISSUE TITLE
[backend] - create tests for epic API

### ISSUE THREAD

**Issue by acivitillo** [dyvenia/timeflow#26]
Description: testing all Epic API endpoints with pytest.

### Tasks

- [ ] create a test for the get endpoint "/{epic_name}" https://github.com/dyvenia/timesheets/pull/32
- [ ] create a test for the post endpoint "/" https://github.com/dyvenia/timesheets/pull/30
- [ ] create a test for the put endpoint "/" https://github.com/dyvenia/timesheets/pull/33
- [ ] create a test for the delete endpoint "/" https://github.com/dyvenia/timesheets/pull/30

### Acceptance Criteria

All Epic API endpoints are tested with the pytest tool and the module is in /tests/api_epic.py

@jkrobicki please put the PR link next to each task checkbox when you are finished with the task so we keep track of which PR solves which task

**Comment by jkrobicki** [comment]
### Issue
- how to override database settings for testing

**Comment by jkrobicki** [comment]
### Override Issue solved
- new get_session() function created in utils
- new dependency created in epic endpoints using fastAPI Dependency
- get_session overridden in tests using app.dependency_overrides

**Comment by jkrobicki** [comment]
@acivitillo I'm now working on 1st and 3rd task. After every task I'll PR. Then I'll create new Issue for testing client API

**Comment by jkrobicki** [comment]
@acivitillo I have a question regarding put method in this issue, as it should be changed too then. 
 When there is an endpoint "/{epic_id}" I can use more query parameters, and have them all in one function: 
- `http://127.0.0.1:8000/api/epics/1?new_epic_name=dyvenia&new_work_area=DYV_update`
 
When there is endpoint "/{epic_id}/new-name" I have to write new methods for every updated parameter, however it looks cleaner
- `http://127.0.0.1:8000/api/epics/1/new-name?new_name=dyvenia`

Do you prefer second option same as for client api?

**Comment by acivitillo** [comment]
correct, but close first the client PR
